<Project>
    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <LangVersion>latest</LangVersion>
        <Authors>Ivan Zhmur</Authors>
        <RepositoryUrl>https://github.com/benotar/Eventify.git</RepositoryUrl>
        <RepositoryType>Git</RepositoryType>
    </PropertyGroup>
</Project>