<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <PackageReference Include="FluentValidation" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
        <PackageReference Include="Microsoft.Extensions.Options.DataAnnotations" />
        <PackageReference Include="Scrutor" />
        <PackageReference Include="Serilog" />
    </ItemGroup>

</Project>