name: Build

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          global-json-file: global.json

      - name: Restore
        run: dotnet restore Eventify.slnx

      - name: Code style check
        run: dotnet format Eventify.slnx --verify-no-changes

      - name: Build
        run: dotnet build Eventify.slnx --configuration Release --no-restore

      - name: Test
        run: dotnet test Eventify.slnx --configuration Release --no-restore --no-build
